org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.1.8-hotspot
# Turn the following on once you finished changing your settings/build:
# org.gradle.configuration-cache=true
# org.gradle.caching=true

# Optional Hytale location for the Assets.zip resolution:
hytale.home_path=C:/Users/Moxinat/AppData/Roaming/Hytale
